version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: loyalty-service-server
    ports:
      - "50052:50052"
    env_file:
      - .env
    volumes:
      - ./server:/app
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: loyalty-service-client
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./client:/app
